//! Phase G courts: exhaustive inverse proceduralization.
//!
//! Each court is a **raster-origin** sequence (frames generated by an
//! independent deterministic generator — never by the encoder) that is pushed
//! through `inverse::encode_frames`, whose exhaustive per-frame candidate
//! space is: UNCHANGED · FILL · CLEAR-ONLY · EXACT_OBJECT_REF · RAW · SPARSE
//! (persistent overlay commit) · one-shot RESIDUAL / RANS_RESIDUAL · COPY_RECT
//! (wrap, screen-scroll, prev-diff composites) · TRANSLATION.
//!
//! Every emitted stream must decode with the normative decoder to byte-
//! identical rasters (`report.exact`); the winning family per frame must be
//! the measured low-cost explanation for the court's content; and the oracle
//! records (winner == min over every evaluated family) must be consistent.
//! The noise negative control proves RAW fallback with bounded overhead.

use vole_video::{
    error::VoleError,
    inverse::{self, EncodeOptions, SearchSpace},
    pixel::Canvas,
};

/// Deterministic xorshift64* byte source.
struct Det(u64);
impl Det {
    fn next(&mut self) -> u64 {
        let mut x = self.0.max(1);
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        x = x.wrapping_mul(0x2545_F491_4F6C_DD1D);
        self.0 = x;
        x
    }
    fn byte(&mut self) -> u8 {
        (self.next() >> 56) as u8
    }
}

fn canvas_of(w: u32, h: u32, data: Vec<u8>) -> Canvas {
    Canvas::from_parts(w, h, data).expect("canvas")
}

fn uniform(w: u32, h: u32, v: u8) -> Canvas {
    canvas_of(w, h, vec![v; (w * h) as usize])
}

/// Independent painter: clear to `bg`, then blit boxes in paint order.
fn paint_boxes(w: u32, h: u32, bg: u8, boxes: &[(i64, i64, u32, u32, u8)]) -> Canvas {
    let mut data = vec![bg; (w * h) as usize];
    for (bx, by, bw, bh, v) in boxes {
        for dy in 0..*bh as i64 {
            for dx in 0..*bw as i64 {
                let x = bx + dx;
                let y = by + dy;
                if x >= 0 && y >= 0 && x < i64::from(w) && y < i64::from(h) {
                    data[y as usize * w as usize + x as usize] = *v;
                }
            }
        }
    }
    canvas_of(w, h, data)
}

fn no_sweep() -> EncodeOptions {
    EncodeOptions {
        bg_sweep: false,
        ..EncodeOptions::default()
    }
}

// ---------------------------------------------------------------------------
// Courts
// ---------------------------------------------------------------------------

#[test]
fn static_identical_sequence_is_the_unchanged_lane() -> Result<(), VoleError> {
    let (w, h) = (48u32, 32u32);
    let f0 = paint_boxes(w, h, 90, &[(10, 8, 12, 8, 200), (30, 20, 6, 6, 40)]);
    let frames = std::iter::repeat_n(f0, 40).collect::<Vec<_>>();
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    assert_eq!(report.frame_count, 40);
    // Every interval after the checkpoint must be the zero-transition lane.
    for d in report.decisions.iter().skip(1) {
        assert_eq!(d.winner_family, "unchanged");
        assert!(d.emitted.is_empty());
        assert_eq!(d.winner_payload_bytes, 13);
    }
    // Amortized cost must be a tiny fraction of raw raster bytes (the F0
    // object declaration dominates a small canvas, so compare amortized).
    let amortized = report.vole.len() as f64 / report.frame_count as f64;
    assert!(amortized < 120.0, "amortized {amortized} B/frame too high");
    assert!((report.vole.len() as u64) * 20 < report.raw_raster_bytes);
    Ok(())
}

#[test]
fn blinking_pixel_over_static_base_is_sparse() -> Result<(), VoleError> {
    let (w, h) = (48u32, 32u32);
    // Base: uniform 90 canvas with a persistent box at (8,8,20x10) value 128.
    let base = paint_boxes(w, h, 90, &[(8, 8, 20, 10, 128)]);
    let mut frames = Vec::new();
    frames.push(base.clone());
    // A pixel blinks 200 <-> 10 for 16 frames.
    for k in 0..16u8 {
        let v = if k % 2 == 0 { 200 } else { 10 };
        let idx = 30 * w as usize + 40;
        let (_, _, mut data) = base.clone().into_parts();
        data[idx] = v;
        frames.push(canvas_of(w, h, data));
    }
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    for d in report.decisions.iter().skip(1) {
        assert_eq!(d.winner_family, "sparse");
        assert_eq!(d.residual_points, 1);
    }
    // Sparse cost scales with changed pixels, not frames.
    assert!((report.vole.len() as u64) * 8 < report.raw_raster_bytes);
    Ok(())
}

#[test]
fn cycling_uniform_frames_reuse_fill_objects() -> Result<(), VoleError> {
    let (w, h) = (32u32, 32u32);
    let mut frames = Vec::new();
    for k in 0..12 {
        frames.push(uniform(w, h, if k % 2 == 0 { 200 } else { 60 }));
    }
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    // The winner families must come from the replacement/fill family set and
    // later B-frames must reuse the declared fill object (exact_ref).
    let families: Vec<&str> = report.decisions.iter().map(|d| d.winner_family).collect();
    for f in &families {
        assert!(
            matches!(*f, "fill" | "raw" | "exact_ref"),
            "unexpected family {f}"
        );
    }
    // Second B frame (index 3) must reuse the object declared at index 1.
    assert_eq!(families[1], "raw");
    assert_eq!(families[3], "exact_ref");
    assert_eq!(families[5], "exact_ref");
    // Uniform frames must cost a few tens of bytes, not raster bytes.
    assert!((report.vole.len() as u64) * 10 < report.raw_raster_bytes);
    Ok(())
}

#[test]
fn diagonal_pan_is_integer_translation() -> Result<(), VoleError> {
    let (w, h) = (48u32, 32u32);
    let mut frames = Vec::new();
    for k in 0..12i64 {
        // A 10x6 box gliding diagonally (vx=vy=1) over uniform 90.
        frames.push(paint_boxes(w, h, 90, &[(10 + k, 6 + k, 10, 6, 180)]));
    }
    let report = inverse::encode_frames(&frames, &EncodeOptions::default())?;
    assert!(report.exact);
    assert_eq!(
        report.background, 90,
        "sweep must pick the scene background"
    );
    for d in report.decisions.iter().skip(1) {
        assert_eq!(d.winner_family, "translation");
    }
    // Raster-only baseline must be much larger than the procedural encoding.
    let raster_only = inverse::encode_frames(
        &frames,
        &EncodeOptions {
            raster_only: true,
            ..EncodeOptions::default()
        },
    )?;
    assert!(raster_only.exact);
    assert!(
        raster_only.vole.len() > report.vole.len() * 8,
        "raster-only {}B should dwarf procedural {}B",
        raster_only.vole.len(),
        report.vole.len()
    );
    Ok(())
}

#[test]
fn whole_canvas_wrap_scroll_is_copy_rect() -> Result<(), VoleError> {
    let (w, h) = (32u32, 32u32);
    // Rows carry their index (non-periodic vertically).
    let f0 = canvas_of(w, h, {
        let mut d = Vec::with_capacity((w * h) as usize);
        for r in 0..h {
            for _ in 0..w {
                d.push((r % 256) as u8);
            }
        }
        d
    });
    let s = 3i64;
    let mut frames = Vec::new();
    frames.push(f0.clone());
    for t in 1..=10u32 {
        // Independent oracle: row y of frame t == row (y + t*s) mod H.
        let mut d = Vec::with_capacity((w * h) as usize);
        for y in 0..h as usize {
            let src = (y + (t as usize) * (s as usize)) % h as usize;
            let row = &f0.as_slice()[src * w as usize..(src + 1) * w as usize];
            d.extend_from_slice(row);
        }
        frames.push(canvas_of(w, h, d));
    }
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    for d in report.decisions.iter().skip(1) {
        assert_eq!(
            d.winner_family, "copy_rect",
            "frame {} must be COPY_RECT",
            d.frame
        );
        assert_eq!(d.residual_points, 0);
        // Two rects + envelope per scroll frame (~63 B) against a 1024 B frame.
        let raw_frame = report.raw_raster_bytes / report.frame_count;
        assert!(
            d.winner_payload_bytes < raw_frame / 10,
            "scroll interval too costly"
        );
    }
    Ok(())
}

#[test]
fn screen_scroll_with_new_rows_is_copy_plus_residual() -> Result<(), VoleError> {
    let (w, h) = (32u32, 24u32);
    // Deterministic "terminal-ish" content: rows of pseudo-text over a ruler
    // background. Content scrolls up by 2 rows each frame; the bottom 2 rows
    // are brand-new noise-like content (never present in the prior frame).
    let mut rng = Det(0xC0FFEE);
    let mut frame_data = Vec::new();
    for _ in 0..h {
        let mut row = Vec::with_capacity(w as usize);
        for _ in 0..w {
            row.push(if rng.byte().is_multiple_of(4) {
                rng.byte()
            } else {
                32
            });
        }
        frame_data.push(row);
    }
    let mut frames = Vec::new();
    frames.push(canvas_of(w, h, frame_data.concat()));
    let s = 2usize;
    for _ in 1..=8 {
        let prev = frames.last().unwrap();
        let mut d = Vec::with_capacity((w * h) as usize);
        // Rows [s..H) move to the top.
        for y in s..h as usize {
            d.extend_from_slice(&prev.as_slice()[y * w as usize..(y + 1) * w as usize]);
        }
        // New rows enter at the bottom (independent deterministic content).
        for _ in 0..s {
            for _ in 0..w {
                d.push(if rng.byte().is_multiple_of(4) {
                    rng.byte()
                } else {
                    32
                });
            }
        }
        frames.push(canvas_of(w, h, d));
    }
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    // The scroll must be found: no frame may fall back to a full RAW raster.
    for d in report.decisions.iter().skip(1) {
        assert_ne!(d.winner_family, "raw", "scroll frame fell back to RAW");
        assert!(
            matches!(d.winner_family, "copy_rect" | "copy_residual"),
            "unexpected family {}",
            d.winner_family
        );
    }
    // The whole stream stays below the literal raster size.
    assert!(report.vole.len() as u64 <= report.raw_raster_bytes);
    Ok(())
}

#[test]
fn noise_negative_control_falls_back_to_raw_with_bounded_overhead() -> Result<(), VoleError> {
    let (w, h) = (32u32, 32u32);
    let mut rng = Det(0x5EED_1234);
    let mut frames = Vec::new();
    for _ in 0..8 {
        let mut d = Vec::with_capacity((w * h) as usize);
        for _ in 0..(w * h) {
            d.push(rng.byte());
        }
        frames.push(canvas_of(w, h, d));
    }
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    for d in &report.decisions {
        assert_eq!(d.winner_family, "raw", "noise must fall back to RAW");
    }
    // Bounded overhead: stream ≈ raw raster bytes + small descriptor envelope.
    let overhead = report.vole.len() as f64 / report.raw_raster_bytes as f64;
    assert!(
        overhead < 1.15,
        "RAW fallback overhead {overhead:.3} must stay bounded"
    );
    Ok(())
}

#[test]
fn object_appearing_over_static_scene_records_rebase() -> Result<(), VoleError> {
    let (w, h) = (48u32, 32u32);
    let mut rng = Det(0x5EED_0001);
    let bg_frame = paint_boxes(w, h, 90, &[]);
    let mut frames = Vec::new();
    for _ in 0..4 {
        frames.push(bg_frame.clone());
    }
    // A wholly different scene (full-canvas noise) appears at frame 4 and
    // then stays: no procedural hypothesis over the old base can beat RAW for
    // the appearance frame, and the static run afterwards is the unchanged
    // lane (a measured "rebase" cost: one full-raster declaration).
    let mut noise = Vec::with_capacity((w * h) as usize);
    for _ in 0..(w * h) {
        noise.push(rng.byte());
    }
    let scene_b = canvas_of(w, h, noise);
    for _ in 4..12 {
        frames.push(scene_b.clone());
    }
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    let fams: Vec<&str> = report.decisions.iter().map(|d| d.winner_family).collect();
    assert_eq!(&fams[..4], &["raw", "unchanged", "unchanged", "unchanged"]);
    // The appearance frame must pay a full-raster declaration (rebase).
    assert_eq!(fams[4], "raw");
    assert!(report.decisions[4].object_decl_bytes > 0);
    for d in report.decisions.iter().skip(5) {
        assert_eq!(d.winner_family, "unchanged");
    }
    Ok(())
}

#[test]
fn glitch_then_revert_uses_sparse_correction() -> Result<(), VoleError> {
    let (w, h) = (32u32, 24u32);
    let base = paint_boxes(w, h, 70, &[(4, 4, 20, 10, 150)]);
    let mut frames = vec![base.clone()];
    for k in 0..6u8 {
        let idx = (10 * w + 20) as usize;
        let (_, _, mut data) = base.clone().into_parts();
        data[idx] = if k % 2 == 0 { 255 } else { 70 };
        frames.push(canvas_of(w, h, data));
    }
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    for d in report.decisions.iter().skip(1) {
        assert_eq!(d.winner_family, "sparse");
    }
    Ok(())
}

#[test]
fn oracle_records_are_regret_free_and_consistent() -> Result<(), VoleError> {
    let (w, h) = (24u32, 16u32);
    let mut rng = Det(7);
    let mut frames = Vec::new();
    // A mixed sequence: static, pan, wrap, noise.
    frames.push(paint_boxes(w, h, 90, &[(4, 4, 8, 6, 200)]));
    for k in 1..4 {
        frames.push(paint_boxes(w, h, 90, &[(4 + k, 4 + k, 8, 6, 200)]));
    }
    frames.push(uniform(w, h, 90));
    for k in 0..3 {
        let idx = 5;
        let (_, _, mut data) = paint_boxes(w, h, 90, &[(4 + k, 4, 8, 6, 200)]).into_parts();
        data[idx] = 255;
        frames.push(canvas_of(w, h, data));
    }
    for _ in 0..3 {
        let mut d = Vec::with_capacity((w * h) as usize);
        for _ in 0..(w * h) {
            d.push(rng.byte());
        }
        frames.push(canvas_of(w, h, d));
    }
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    assert_eq!(report.search_space, SearchSpace::Exhaustive);
    for d in &report.decisions {
        // The winner must equal the cheapest valid family (regret 0 within the
        // enumerated space) and every aggregate must be internally consistent.
        let mut min_valid = u64::MAX;
        let mut valid_total = 0u64;
        for f in &d.families {
            assert!(f.evaluated >= f.valid);
            valid_total += f.valid;
            if f.valid > 0 && f.best_payload < min_valid {
                min_valid = f.best_payload;
            }
        }
        assert_eq!(valid_total, d.candidates_valid);
        assert_eq!(min_valid, d.winner_payload_bytes);
        assert!(d.winner_payload_bytes >= d.winner_interval_bytes);
        assert_eq!(d.candidates_valid, d.candidates_valid);
        // The winner was actually materialized and compared.
        assert!(d.materialized_exact);
    }
    // All emitted decisions replay to the identical input raster (exact
    // already asserts this end-to-end); additionally assert decode stability.
    let parsed = vole_video::decoder::decode_bytes(&report.vole)?;
    let decoded = vole_video::decoder::materialize_all(&parsed)?;
    assert_eq!(decoded.len(), frames.len());
    for (a, b) in decoded.iter().zip(frames.iter()) {
        assert!(a.exactly_matches(b));
    }
    Ok(())
}

#[test]
fn background_sweep_picks_the_scene_background() -> Result<(), VoleError> {
    let (w, h) = (40u32, 24u32);
    let mut frames = Vec::new();
    for k in 0..6i64 {
        // Boxes over light-gray 200; exposed regions are 200 in every frame.
        frames.push(paint_boxes(w, h, 200, &[(5 + k, 4, 8, 6, 10)]));
    }
    let report = inverse::encode_frames(&frames, &EncodeOptions::default())?;
    assert!(report.exact);
    assert_eq!(report.background, 200);
    // Every moving frame must be a cheap translation once the sweep chose 200.
    for d in report.decisions.iter().skip(1) {
        assert_eq!(d.winner_family, "translation");
    }
    Ok(())
}

#[test]
fn single_frame_and_mismatched_canvases_are_handled() -> Result<(), VoleError> {
    // A single frame encodes as checkpoint only.
    let one = vec![uniform(16, 16, 7)];
    let report = inverse::encode_frames(&one, &no_sweep())?;
    assert!(report.exact);
    assert_eq!(report.decisions.len(), 1);
    // Mismatched canvases are a typed error, not a panic.
    let bad = vec![uniform(16, 16, 7), uniform(17, 16, 7)];
    assert_eq!(
        inverse::encode_frames(&bad, &no_sweep()).unwrap_err(),
        VoleError::ObjectGeometryMismatch
    );
    Ok(())
}

#[test]
fn large_canvas_uses_hash_prefiltered_scroll_search_and_stays_exact() -> Result<(), VoleError> {
    // 320x64 = 20480 samples > the full-scan gate, so the 1D scroll families
    // run in row-hash-prefiltered mode while every other family is exhaustive.
    let (w, h) = (320u32, 64u32);
    let mut rng = Det(0xBEEF_2024);
    let mut row0 = Vec::with_capacity((w * h) as usize);
    for y in 0..h {
        for _ in 0..w {
            row0.push((y % 251) as u8 ^ (rng.byte() & 0x0F));
        }
    }
    let f0 = canvas_of(w, h, row0);
    let s = 2usize;
    let mut frames = vec![f0.clone()];
    for _ in 1..=6 {
        let prev = frames.last().unwrap();
        let mut d = Vec::with_capacity((w * h) as usize);
        for y in s..h as usize {
            d.extend_from_slice(&prev.as_slice()[y * w as usize..(y + 1) * w as usize]);
        }
        for _ in 0..s {
            for _ in 0..w {
                d.push(rng.byte());
            }
        }
        frames.push(canvas_of(w, h, d));
    }
    let report = inverse::encode_frames(&frames, &no_sweep())?;
    assert!(report.exact);
    assert_eq!(report.search_space, inverse::SearchSpace::HashPrefiltered);
    for d in report.decisions.iter().skip(1) {
        assert_ne!(d.winner_family, "raw", "scroll frame fell back to RAW");
        assert!(
            matches!(d.winner_family, "copy_rect" | "copy_residual"),
            "unexpected family {}",
            d.winner_family
        );
    }
    Ok(())
}
